version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    env_file:
      - .env.temp

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    networks:
      - inception_network
    env_file:
      - .env.temp
    volumes:
      - db_data:/var/lib/mysql

networks:
  inception_network:

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/imisumi-wsl/dev/Inception/db_data
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/imisumi-wsl/dev/Inception/wp_data
      o: bind